### ISSUE TITLE
Breaks collab_client.js test?

### ISSUE THREAD

**Issue by webzwo0i** [ether/ep_cursortrace#26]
When this plugin is installed, the [collab_client test](https://github.com/ether/etherpad-lite/blob/develop/src/tests/frontend/specs/collab_client.js) fails with
```
Error: waitFor condition never became true () => helper.padInner$('div').eq(0).text() === user1Text
    at Object.helper.waitFor (helper.js:206:9)
    at Object.helper.waitForPromise (helper.js:253:59)
    at http://localhost:9001/javascripts/lib/ep_etherpad-lite/tests/frontend/specs/collab_client.js?callback=testRunnerRequire.define:80:76
    at Object.performAsOtherUser (helper/multipleUsers.js:27:11)
    at Context.<anonymous> (http://localhost:9001/javascripts/lib/ep_etherpad-lite/tests/frontend/specs/collab_client.js?callback=testRunnerRequire.define:80:32)
```

Not sure if it's a problem with the test or with ep_cursortrace

**Comment by JohnMcLear** [comment]
The linked test (`tests/frontend/specs/collab_client.js`) was removed when Etherpad migrated from the custom in-browser mocha harness to Playwright in 2.x. The old mocha-in-iframe runner — and its `helper.waitForPromise` / `multipleUsers` helpers — no longer exist, so this failure mode can no longer occur. Closing as stale. If the new Playwright collab tests fail with `ep_cursortrace` installed, please open a fresh issue with that trace.
